// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjsThHfLoTWV59uLI6qsOA_Dnr0QNmyqk',
    appId: '1:410526087309:web:c93ebc979a92a272838ac4',
    messagingSenderId: '410526087309',
    projectId: 'fir-example-ae7d6',
    authDomain: 'fir-example-ae7d6.firebaseapp.com',
    storageBucket: 'fir-example-ae7d6.appspot.com',
    measurementId: 'G-VXD04MV636',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBo6EQ6zQouQyoz0zVUIe2Z_8Sf51Ln8',
    appId: '1:410526087309:android:b13c947ca56cbd69838ac4',
    messagingSenderId: '410526087309',
    projectId: 'fir-example-ae7d6',
    storageBucket: 'fir-example-ae7d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqSQBVuWoPwF09JXpKVy30h6QAKWsvhaM',
    appId: '1:410526087309:ios:212428e711bba064838ac4',
    messagingSenderId: '410526087309',
    projectId: 'fir-example-ae7d6',
    storageBucket: 'fir-example-ae7d6.appspot.com',
    iosClientId: '410526087309-7n69rrpjolq23l0gtcvdrlqvb55hqghj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProjectTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqSQBVuWoPwF09JXpKVy30h6QAKWsvhaM',
    appId: '1:410526087309:ios:212428e711bba064838ac4',
    messagingSenderId: '410526087309',
    projectId: 'fir-example-ae7d6',
    storageBucket: 'fir-example-ae7d6.appspot.com',
    iosClientId: '410526087309-7n69rrpjolq23l0gtcvdrlqvb55hqghj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProjectTemplate',
  );
}
